<?php require __DIR__ . '/../partials/head.php'; require __DIR__ . '/../partials/header.php'; ?>
<main id="main">
    <section class="motion-section about-hero about-hero--purpose"><div class="container">
        <span class="eyebrow">THE THINKING BEHIND LINKEASY SOCIAL</span>
        <h1>Build a presence.<br><span>Not a pile of tasks.</span></h1>
        <div class="about-hero-bottom"><p>LinkEasy Social starts with a simple belief: keeping up with your channels shouldn’t take you away from the people you’re trying to reach.</p><a class="text-link" href="#our-purpose">Our purpose <svg class="icon"><use href="#i-chevron-down"/></svg></a></div>
        <div class="about-purpose-board" aria-label="Our product direction: idea, plan, publish, learn">
            <div class="about-board-brand"><img src="<?= e(asset(config('brand.logo_light'))) ?>" width="54" height="54" alt=""><div><strong>LinkEasy Social</strong><span>Less scattered work. More connected thinking.</span></div></div>
            <div class="about-purpose-loop"><?php foreach ([['edit','01','Make room for an idea','Start with what you want to say.'],['calendar','02','Give it a place in the week','A rhythm you can keep up with.'],['send','03','Show up on your channels','Shape content for each audience.'],['bar-chart','04','Learn and go again','Let the response inform the next idea.']] as [$icon,$num,$title,$text]): ?><div class="about-purpose-step"><span class="about-step-top"><svg class="icon"><use href="#i-<?= $icon ?>"/></svg><small><?= $num ?></small></span><h3><?= $title ?></h3><p><?= $text ?></p></div><?php endforeach; ?></div>
            <div class="about-board-foot"><span class="command-signal"></span> OUR PRODUCT DIRECTION <span>One thoughtful loop, rather than four disconnected jobs.</span></div>
        </div>
    </div></section>
    <section class="motion-section section" id="our-purpose"><div class="container about-editorial"><div><span class="eyebrow">01 / OUR PURPOSE</span><h2>The work between<br>the posts matters.</h2></div><div class="about-prose"><p class="about-lead">The caption is only part of the job. There are accounts to switch, images to find, dates to remember and results to make sense of.</p><p>LinkEasy Social is being built to bring those pieces closer together. The purpose is not simply to help people post more. It is to make the path from an idea to a consistent social presence easier to follow.</p><p>For a creator, that might mean planning around a busy week. For a business, it means giving content a routine instead of leaving it until the last minute. For an agency, it means keeping each client’s work in its own context.</p><p>That everyday coordination—not another dashboard for its own sake—is the problem we want to solve.</p></div></div></section>
    <section class="motion-section section section-soft"><div class="container about-editorial"><div><span class="eyebrow">02 / OUR VISION</span><h2>One place to work.<br>Room to do it your way.</h2></div><div class="about-prose"><p>Our vision for LinkEasy Social is a connected workspace where planning, publishing and learning feel like parts of the same process. A place that makes the next step clear without deciding your voice, your pace or your goals for you.</p><p>Choice matters here. Some people are comfortable bringing their own API credentials. Others need help getting started, or prefer a managed plan. Those should be different ways into the same hosted product—not a requirement to run your own server.</p><p>We want the product to feel useful on an ordinary working day: understandable enough to get started, organized enough to return to, and honest about the limits of each network.</p></div></div></section>
    <section class="motion-section section"><div class="container"><div class="section-head"><span class="eyebrow">03 / WHAT WE BELIEVE</span><h2>A few thoughts<br>that guide the details.</h2><p>The choices behind LinkEasy Social matter as much as the feature list.</p></div><div class="about-values">
        <?php foreach ([['01','Consistency over noise','A sustainable rhythm is more useful than pressure to publish everywhere, all the time. Planning should protect your attention, not fill every empty slot.','calendar-check'],['02','Control without confusion','Your accounts should remain yours. Bringing API credentials is a choice, and setup help should explain what is being connected—not hide it behind technical language.','key'],['03','Clarity before promises','A sample dashboard is not live activity. A planned integration is not an available one. Provider approvals, quotas and fees need to be part of the conversation.','shield-check']] as [$num,$title,$text,$icon]): ?><article><span class="about-value-num"><?= $num ?></span><svg class="icon"><use href="#i-<?= $icon ?>"/></svg><h3><?= $title ?></h3><p><?= $text ?></p></article><?php endforeach; ?>
    </div></div></section>
    <section class="motion-section section about-team-section" id="our-team"><div class="container"><div class="about-editorial"><div><span class="eyebrow">04 / THE TEAM APPROACH</span><h2>Different disciplines.<br>The same useful question.</h2></div><div class="about-prose"><p class="about-lead">“Does this make the work clearer for the person using it?”</p><p>That is the question connecting product decisions, interface design, integrations and setup guidance. These are the functions that guide how we build and support the product.</p></div></div>
        <div class="about-team-functions"><?php foreach ([['layers','Product & workflow','Start with the everyday job.','Keep ideas, planning and account context connected, so the product follows the way people actually work.'],['grid','Design & experience','Make the next step clear.','Care about the labels, the small-screen layout and the moments when someone needs guidance rather than another setting.'],['plug','Engineering & integrations','Respect the networks.','Treat permissions, provider rules and reliable account handling as essential parts of the experience—not details to work around.'],['message','Setup & support','Turn questions into context.','Understand the channels and goals first, explain the options plainly, and agree on the scope before paid setup begins.']] as [$icon,$title,$tag,$text]): ?><article><span class="about-role-icon"><svg class="icon"><use href="#i-<?= $icon ?>"/></svg></span><div><h3><?= $title ?></h3><strong><?= $tag ?></strong><p><?= $text ?></p></div></article><?php endforeach; ?></div>
        <div class="about-feedback"><svg class="icon"><use href="#i-message"/></svg><p><strong>Your workflow belongs in the conversation.</strong> Tell us what feels repetitive, what gets lost between tools, or what would make setup easier. Specific questions help shape better decisions.</p><a class="text-link" href="<?= e(url('contact')) ?>">Share a thought <svg class="icon"><use href="#i-arrow-up-right"/></svg></a></div>
    </div></section>
    <section class="motion-section section about-choice"><div class="container about-editorial"><div><span class="eyebrow eyebrow--light">05 / A PRACTICAL WAY IN</span><h2>Your keys.<br>Or a helping hand.</h2></div><div><p>Bring Your Own API runs on LinkEasy Social’s hosted platform. It allows unlimited connected accounts and has no platform daily, weekly or monthly posting quotas; each provider’s limits and API fees still apply.</p><p>Prefer help? One-Time Setup is a custom-quoted service based on your needs, with the same account and platform-quota allowances. There is no recurring platform fee for BYO API or One-Time Setup while the app operates. That is not a guarantee of perpetual service or an exemption from provider charges.</p><p>Free and Managed have their own plan limits. Choose based on your workflow, not an assumption that every option includes the same allowances.</p><a class="btn btn-primary" href="<?= e(url('pricing')) ?>">Compare the options <svg class="icon"><use href="#i-arrow-right"/></svg></a></div></div></section>
    <section class="motion-section section"><div class="container about-closing"><span class="eyebrow">LET’S START WITH WHAT YOU NEED</span><h2>Your next chapter<br>doesn’t need more tabs.</h2><p>Tell us about your channels and the way you want to work. We’ll start there.</p><div class="about-closing-actions"><a class="btn btn-dark" href="<?= e(url('contact')) ?>?subject=One-Time%20Setup">Talk about your setup <svg class="icon"><use href="#i-arrow-up-right"/></svg></a><a class="text-link" href="<?= e(url('legal')) ?>">Our policies & commitments</a></div></div></section>
</main>
<?php require __DIR__ . '/../partials/footer.php'; ?>
