<?php require __DIR__ . '/../partials/head.php'; require __DIR__ . '/../partials/header.php'; ?>
<main id="main">
    <section class="subpage-hero"><div class="container"><span class="eyebrow">Help &amp; getting started</span><h1>A clearer next step.</h1><p>Choose your setup, understand API requirements, and find the right support for your workspace.</p></div></section>
    <section class="section"><div class="container resource-grid">
        <?php foreach ([['user','Create your account','Start with an email and password or use Google sign-in when configured. New accounts start on Free; BYO API access and setup are arranged with our team.','signup','Create an account'],['key','Bring your credentials','Request BYO API access, then follow the provider’s developer-app and authorization requirements. Keep secrets out of public messages. Never use keys that belong to someone else.','contact','Ask about BYO API'],['rocket','Let us help with setup','Tell us which networks and channels you manage. We will agree a one-time onboarding scope and quote before starting. You keep responsibility for provider API costs.','contact','Request a quote'],['plug','Connect eligible accounts','Each network may require particular account types, permissions or app approval. Multiple channels must each be authorized. A connection does not guarantee access to every API feature.','integrations','Explore connections'],['credit-card','Understand billing','Free and Managed have their published allowances. BYO API and One-Time Setup allow unlimited accounts, subject to provider rules. Manage subscription renewal in PayPal or contact support.','refunds','Billing guidance'],['shield','Manage your data','Ask for data access, correction or deletion from your account email. You can separately revoke provider access in the network’s connected-app settings.','data_deletion','Data & privacy requests']] as [$icon,$title,$text,$route,$cta]): ?>
        <article class="resource-card"><span class="module-icon tone-blue"><svg class="icon"><use href="#i-<?= $icon ?>"/></svg></span><h2><?= e($title) ?></h2><p><?= e($text) ?></p><a class="resource-read" href="<?= e(url($route)) ?>"><?= e($cta) ?> <svg class="icon"><use href="#i-arrow-right"/></svg></a></article>
        <?php endforeach; ?>
    </div></section>
    <section class="section section-soft"><div class="container"><div class="section-head"><span class="eyebrow">Common questions</span><h2>A little clarity goes a long way.</h2></div><div class="help-faqs"><?php foreach (config('faqs') as $faq): ?><details><summary><?= e($faq['q']) ?></summary><p><?= e($faq['a']) ?></p></details><?php endforeach; ?></div></div></section>
</main>
<?php require __DIR__ . '/../partials/footer.php'; ?>
